//! Checks `brace::expand` against real bash's own expansion output (pulled
//! from brace-expansion's test/bash-results.txt, generated by actually
//! running bash - see test/generate.sh in that package) plus its targeted
//! unit test cases (sequences, padding, nesting, ordering).

use rs_minimatch_core::brace_expand;
use serde::Deserialize;

fn fixture<T: for<'de> Deserialize<'de>>(name: &str) -> Vec<T> {
    let path = format!("{}/tests/fixtures/{name}.json", env!("CARGO_MANIFEST_DIR"));
    let data = std::fs::read_to_string(&path).unwrap_or_else(|e| panic!("read {path}: {e}"));
    serde_json::from_str(&data).unwrap_or_else(|e| panic!("parse {path}: {e}"))
}

#[derive(Deserialize)]
struct Case {
    pattern: String,
    expected: Vec<String>,
}

#[test]
fn matches_real_bash_expansions() {
    let cases: Vec<Case> = fixture("brace_bash_comparison");
    assert!(!cases.is_empty());
    let mut failures = Vec::new();
    for case in &cases {
        let actual = brace_expand(&case.pattern);
        if actual != case.expected {
            failures.push(format!("{:?}: got {:?}, want {:?}", case.pattern, actual, case.expected));
        }
    }
    assert!(failures.is_empty(), "{} failures:\n{}", failures.len(), failures.join("\n"));
}

#[derive(Deserialize)]
struct TargetedCase {
    pattern: String,
    expected: Vec<String>,
    source: String,
}

#[test]
fn matches_targeted_unit_tests() {
    let cases: Vec<TargetedCase> = fixture("brace_targeted");
    assert!(!cases.is_empty());
    let mut failures = Vec::new();
    for case in &cases {
        let actual = brace_expand(&case.pattern);
        if actual != case.expected {
            failures.push(format!(
                "[{}] {:?}: got {:?}, want {:?}",
                case.source, case.pattern, actual, case.expected
            ));
        }
    }
    assert!(failures.is_empty(), "{} failures:\n{}", failures.len(), failures.join("\n"));
}
